### ISSUE TITLE
major mode not changing

### ISSUE THREAD

**Issue by jabranham** [vspinu/polymode#97]
Hi, and thanks for the great package. 

About a week ago, polymode was working great for me in Rmd files. Now it treats the whole buffer as markdown mode. Was there an update that would cause this? 

Here's how I load it in my dotemacs file:

```
(use-package polymode 
  :ensure t
  :mode
  ("\\.Snw" . poly-noweb+r-mode)
  ("\\.Rnw" . poly-noweb+r-mode)
  ("\\.Rmd" . poly-markdown+r-mode))
```

Update: after some more exploration, I get this error when I try to start a new code chunk:

`(poly-lock-fontify-region 141 166) -> (font-lock-default-fontify-region 141 166 nil): Args out of range: 164, 167 `

which makes me think this may be related to: https://github.com/vspinu/polymode/issues/87 

Here's another error that pops up as well: 

`Making font-lock-fontified buffer-local while locally let-bound!`

**Comment by vspinu** [comment]
There was a small change in markdown regexp last week. I doubt it should cause this error. 

Would you mind sharing the problematic rmd file?

**Comment by jabranham** [comment]
It happens in all Rmd files, so as an example:

```
---
title: example
output:
    pdf_document:
        keep_tex: true
---

```{r mytab, fig.cap = "My table"}
library(ggplot2)
ggplot(mtcars, aes(mpg, wt)) + geom_point()
```

```

Weirdly, I use the same dotemacs file on another computer with the same version of polymode and it works perfectly.

**Comment by vspinu** [comment]
Hm. It's probably a regexp issue. Could you `M-x regex-builder` then paste this regexp `"```[ \t]*\\(?:{\\|lang=\\)?\\([^ \t\n]+\\)"`. It should highlight markdown header with language feature. 

Are you completely sure it was working before? Make sure you indeed load the correct version of polymode and not some outdated elc file.

**Comment by jabranham** [comment]
Yes, it did so. 

Yes, totally certain that it was working before. I only have the one version of polymode on my computer - it's the most recent MELPA build - `polymode-20160502.922`.

**Comment by vspinu** [comment]
Should be fixed. It was a regexp thing, funny part is that `'''{r }`, `'''r` and `'''{r something}` where all working but plain `'''{r}` not. Thanks for the report.

**Comment by mmaechler** [comment]
Thanks for the fix...  it was a bit of a shock.. .. but your fix came so promptly!

**Comment by jabranham** [comment]
Hi @vspinu - 

I just updated from MELPA and am still having this same issue. I'm still getting the 
`Making font-lock-fontified buffer-local while locally let-bound!` message when starting R chunks...

**Comment by mmaechler** [comment]
I also still see the message `Making font-lock-fontified buffer-local while locally let-bound!` ... not regularly but for instance when I'm in an `foo.Rmd` file  and then do  C-x C-v <another *.Rmd>
at the time the other file is opened / the new *.Rmd buffer created, I still get the above message.

It's not a big deal though... Everything seems to continue to work fine.

**Comment by vspinu** [comment]
> Making font-lock-fontified buffer-local while locally let-bound!

This is emacs 24. I was wondering why I don't see it. I have removed that let-bound which fixes that warning.
